#!/usr/bin/env python3
"""Regenerate the P5.4 opcode-matrix ratchet files (see README.md).

Reads the deterministic feed merges + the deep Test262-dynamic merge,
completes the closed cell universe from opcodes.txt, and writes
ratchet.json + justifications.toml. Copies nothing: test262-dynamic.json
is refreshed by hand (campaign + `--merge`, see README) because the
Test262 dynamic campaign is slow and flaky by nature (pathological
regex/temporal tests need timeouts + subdivision).

Closed universe: every base opcode in opcodes.txt, both arms of the 9
conditional jumps, argv-0..7+many of the 4 fixed-arity calls, and both
StoreLiteral shapes. Closed cells missing from every feed become zero
rows with TEMPLATE [zero] reasons: regen prints a loud warning for each,
and the commit must replace the template with a human reason (a template
reason is a placeholder, never a justification). Cells with deep-only
evidence become [deep] entries (family-templated reasons, stable across
regens since they cite presence, not counts).

Usage (from tests/fuzz):
  python3 matrix/regen.py <deterministic.json> <deep.json>
Writes matrix/ratchet.json + matrix/justifications.toml in place, then
self-verifies with `matrix --check` (fresh = the deterministic inputs).
"""

import json
import subprocess
import sys
from pathlib import Path

CONDITIONALS = [
    "JumpIfTrue",
    "JumpIfFalse",
    "JumpIfNotUndefined",
    "JumpIfNullOrUndefined",
    "JumpIfNotLessThan",
    "JumpIfNotLessThanOrEqual",
    "JumpIfNotGreaterThan",
    "JumpIfNotGreaterThanOrEqual",
    "JumpIfNotEqual",
]
ARITY_OPS = ["Call", "SuperCall", "New", "CallEval"]

MATRIX = Path(__file__).resolve().parent


def closed_universe(opcodes):
    cells = list(opcodes)
    for cond in CONDITIONALS:
        cells += [f"{cond}|taken", f"{cond}|nottaken"]
    for op in ARITY_OPS:
        cells += [f"{op}|argv-{n}" for n in range(8)] + [f"{op}|argv-many"]
    cells += ["StoreLiteral|k-str", "StoreLiteral|k-bigint"]
    return cells


def deep_reason(cell):
    if cell == "ImportMeta":
        return (
            "module-only opcode; script-goal deterministic feeds cannot emit "
            "it; dynamic evidence in test262-dynamic.json"
        )
    if "|err-" in cell:
        op, kind = cell.split("|err-", 1)
        return (
            f"{op} surfacing {kind} has evidence only in "
            "test262-dynamic.json (open err family; deterministic feeds "
            "never raise it there)"
        )
    return f"evidence only in test262-dynamic.json: {cell}"


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: regen.py <deterministic.json> <deep.json>")
    det_path = str(Path(sys.argv[1]).resolve())
    deep_path = str(Path(sys.argv[2]).resolve())
    det = json.load(open(det_path))
    deep = json.load(open(deep_path))
    if det["malformed"] or deep["malformed"]:
        sys.exit("refusing to ratchet reports with malformed cells")
    opcodes = (MATRIX / "opcodes.txt").read_text().split()
    det_rows = {m["cell"]: m for m in det["merged"]}
    deep_cells = {m["cell"] for m in deep["merged"]}

    zero_rows = []
    zero_just = {}
    deep_just = {}
    for cell in closed_universe(opcodes):
        if cell in det_rows:
            continue
        if cell in deep_cells:
            deep_just[cell] = deep_reason(cell)
        else:
            zero_rows.append(cell)
            zero_just[cell] = (
                f"TODO(human): {cell} has no evidence in any feed; replace "
                "with a named probe or a written reachability reason"
            )
    for cell in sorted(deep_cells - set(det_rows)):
        if cell not in deep_just:
            deep_just[cell] = deep_reason(cell)

    merged = list(det["merged"])
    for cell in sorted(zero_rows):
        op, _, ref = cell.partition("|")
        merged.append(
            {
                "cell": cell,
                "op": op,
                "refinement": ref or None,
                "static_files": 0,
                "dynamic": 0,
            }
        )
    merged.sort(key=lambda m: m["cell"])
    ratchet = {
        "battery_version": det["battery_version"],
        "sources": ["battery", "battery-opt", "t262-static"],
        "merged": merged,
        "malformed": [],
    }
    (MATRIX / "ratchet.json").write_text(json.dumps(ratchet, indent=2) + "\n")

    lines = [
        "# P5.4 ratchet justifications (generated by regen.py; see README.md).",
        "# [zero]: exact-cell reasons for zero-floor ratchet cells (a zero",
        "# refinement of a zero base inherits the base entry). TEMPLATE reasons",
        "# (TODO(human)) are placeholders: the commit must replace each with a",
        "# named probe or a written reachability reason. Quote every key: TOML",
        "# bare keys cannot contain `|`.",
        "[zero]",
    ]
    for cell in sorted(zero_just):
        lines.append(f'"{cell}" = "{zero_just[cell]}"')
    lines += [
        "# [deep]: cells with evidence ONLY in test262-dynamic.json (periodic",
        "# regen, never gated). Each must be present there and absent from",
        "# deterministic fresh runs (present in fresh means promote to a",
        "# ratchet row). Reasons cite presence, never counts.",
        "[deep]",
    ]
    for cell in sorted(deep_just):
        lines.append(f'"{cell}" = "{deep_just[cell]}"')
    (MATRIX / "justifications.toml").write_text("\n".join(lines) + "\n")

    print(f"ratchet: {len(merged)} rows ({len(zero_rows)} zero)")
    print(f"justifications: {len(zero_just)} zero, {len(deep_just)} deep")
    if zero_rows:
        print("WARNING: template [zero] reasons need human replacement:")
        for cell in sorted(zero_rows):
            print(f"  {cell}")

    # Self-verify: the committed files must pass --check against the same
    # deterministic inputs they were built from.
    tool = ["cargo", "run", "-q", "--release", "--example", "matrix", "--"]
    check = tool + [
        "--check",
        "--ratchet", str(MATRIX / "ratchet.json"),
        "--justifications", str(MATRIX / "justifications.toml"),
        "--deep", deep_path,
        det_path,
    ]
    result = subprocess.run(check, capture_output=True, text=True, cwd=MATRIX.parent)
    print(result.stdout.strip())
    if result.returncode != 0:
        print(result.stderr.strip())
        sys.exit("self-verify FAILED: regen output does not pass --check")


if __name__ == "__main__":
    main()
